### ISSUE TITLE
JSON typing borken

### ISSUE THREAD

**Issue by genehack** [fayland/perl-net-github#61]
f4bf04d8719f0ab73ccd128e4f5f65eed5c0734f has introduced a bug; code that does this:

    my $resp = Net::GitHub->new( %gh_args )->repos->create_fork( $owner , $repo_name );

which used to work, now throws this error:

    Reference bless( do{\(my $o = "")}, 'Cpanel::JSON::XS' ) did not pass type constraint (not isa     JSON::MaybeXS) (in $self->{"json"}) at (eval 163) line 32
        "InstanceOf["JSON::MaybeXS"]" requires that the reference isa JSON::MaybeXS
        The reference (in $self->{"json"}) isa Cpanel::JSON::XS and Exporter

Maybe that type check should be changed to check for all three things `JSON::MaybeXS` might return?

**Comment by karenetheridge** [comment]
> Maybe that type check should be changed to check for all three things JSON::MaybeXS might return?

IMO the type check should be weakened to just 'Object', or use duck-typing -- i.e. `duck_type([ qw(encode decode)]`.  What matters is that you get back an object that implements `encode` and `decode` - the class name that supplies that is irrelevant.

(Plus, if you hardcode the list of things that JSON::MaybeXS can return, it will break if we ever add support for another backend.)

**Comment by fayland** [comment]
Hello. I changed it to Object which should fix the issue. Thanks
