### ISSUE TITLE
Issue Labels API: LabelsID??

### ISSUE THREAD

**Issue by hoppfrosch** [fayland/perl-net-github#62]
Within the implementation of Issue labels API $labelId is needed for most actions: http://search.cpan.org/~fayland/Net-GitHub/lib/Net/GitHub/V3/Issues.pm#Issue_Labels_API

But the github API does not use/provide any $labelId: https://developer.github.com/v3/issues/labels/ - the access is done via $labelName ....

=> Net::Github should also use $labelName instead if $labelId

**Comment by fayland** [comment]
Hi, will take a look this weekend. patches welcome. ty

**Comment by hoppfrosch** [comment]
This seems to be a documentation error only. Just tested your implementation by simply providing $labelName instead $labelId to your functions, and everything works fine.

I will provide a simple patch for your documentation

**Comment by hoppfrosch** [comment]
This seems to be a documentation error only. Just tested your implementation by simply providing $labelName instead $labelId to your functions, and everything works fine.

I will provide a simple patch for your documentation

**Comment by hoppfrosch** [comment]
This seems to be a documentation error only. Just tested your implementation by simply providing $labelName instead $labelId to your functions, and everything works fine.

I will provide a pull request for your documentation

**Comment by hoppfrosch** [comment]
see Pull Request #63
