### ISSUE TITLE
rate limit headers

### ISSUE THREAD

**Issue by kimmel** [fayland/perl-net-github#64]
I just updated to Net::GitHub 0.75 from 0.54 and it broke my program. Prior to 0.60 WWW::Mechanize::GZip was being used to connect to the GitHub API endpoint. This allowed access to the custom response headers GitHub sends about rate limits. LWP::UserAgent does not work the same way so I added rate_limit, rate_limit_remaining, and rate_limit_reset variables to Net::GitHub::V3::Query as a way to expose that data to the developer. The official GitHub Ruby library has these variables as well https://github.com/octokit/octokit.rb/blob/master/lib/octokit/rate_limit.rb

All of that is the first commit. The second commit is just adding more documentation.

**Comment by kimmel** [comment]
Opened pull reguest 65

**Comment by fayland** [comment]
ty, new version uploaded. Thanks
