### ISSUE TITLE
Bug in upload_asset: unknown method 'jsonToObj'

### ISSUE THREAD

**Issue by flatcap** [fayland/perl-net-github#73]
"sub upload_asset" has the line
```
$data = eval { $self->json->jsonToObj($json) };
```
perl doesn't like `jsonToObj` (unknown method).
The other functions use `decode`.
Changing the code to use `decode` fixes thing (for me :-)

**Comment by fayland** [comment]
Sorry for late, fixed. will get a new version out. thanks
