### ISSUE TITLE
TFA?

### ISSUE THREAD

**Issue by jacoby** [fayland/perl-net-github#79]
I'm using two-factor authentication, and I'm willing to open my authenticator and give the number, but I don't see it mentioned (in either Net::GitHub or GitHub docs) how to add it.

Is it best to drop TFA to do this?

**Comment by fayland** [comment]
we do not have it supported I think. but github supports it.

https://developer.github.com/changes/2013-09-03-two-factor-authentication/
https://developer.github.com/v3/auth/#working-with-two-factor-authentication

Patches welcome.

Thanks

**Comment by fayland** [comment]
new version shipped. let us know if any problem. thanks
