### ISSUE TITLE
Can't create GitHub client

### ISSUE THREAD

**Issue by Fvl14** [fayland/perl-net-github#96]
Hi @fayland,

After the latest release(0.97:PR #89), I've faced with issue(example):
**test.pl**
`use strict;
use warnings;
use Net::GitHub::V3;
use TryCatch;
use Data::Dumper;

my $g;

try {

	$g = Net::GitHub::V3->new (
		api_url=> 'https://blabla.com/api/v3',
		access_token => 'token',
	);

} catch($e) {
	print $e;
}

print Dumper $g;`
**FAILED:** **Rate limiting is not enabled. at (eval 491) line 820.**
![image](https://user-images.githubusercontent.com/11509426/77020482-9424d080-698c-11ea-8ca1-e438c205eef2.png)

It looks like I am not able to create Perl GitHub client due to that reason that rate limits are disabled on the server-side.

Could you please fix this issue ASAP or tell me where I am wrong?

CC: @toddr 

Best Regards, Vasyl

**Comment by fayland** [comment]
thanks for the info. I made a rollback for now.

**Comment by toddr** [comment]
I'll look at a new commit in the morning. thanks.

**Comment by toddr** [comment]
https://github.com/fayland/perl-net-github/pull/89/files

**Comment by Fvl14** [comment]
Hi @fayland ,

Thank you so much for the quick fix.
I will close this issue.

Best Regards, Vasyl
